spring.application.name=auth-service
server.port=4005
# Randomly generated jwt secret for testing; wouldn't actually be included here in a real prod system
jwt.secret=vzmZayyZrQ17gCNTOPB2pikyT0Z0qnnLJnwUVRRAfev

