spring.application.name=patient-service

# UNCOMMENT TO USE IN-MEM DATABASE OUTSIDE OF DOCKER:
#spring.datasource.url=jdbc:h2:mem:testdb
##spring.h2.console.path=/h2-console
#spring.h2.console.enabled=true
##spring.datasource.driverClassName=org.h2.Driver
##spring.datasource.username=admin_view
##spring.datasource.password=
## This property not needed, it's set by default:
##spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#####################################################

server.port=4000

logging.level.root=info

# Kafka properties
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer


